### PR TITLE
Expand vars aria

### PR DESCRIPTION
**Pull request by jpcima**
First attempt to fix @redtide's Naked Drums set
Will add some tests later.

### CODE REVIEW

**Comment by jpcima** [comment]
@paulfd Where does the below test come from?
This fails to load in Sforzando, for a reason which I'm not yet fully sure.

Based on some tests I made on my side:
Sforzando will use the shortest name after '$' which matches the name of a known variable.
This behavior would contradict the test case.

(of course the fact this doesn't load in Sfzorzando means there's more to this, but for us it will be OK to raise it as warning and go on permissively)

```
#define $KeyCrash2Edge     52 // Crash Cymbal 2 (Edge)
#define $KeyCrash2     57 // Crash Cymbal 2 (Bow)
#define $Param     10 // Opcode parameter replacement

<region> key=$KeyCrash2Edge sample=../mono_sample.wav
<region> key=$KeyCrash2 sample=../mono_sample.wav
<region> amplitude_oncc$Param=34 sample=../mono_sample.wav
```

**Comment by jpcima** [comment]
Test case above is confirmed incorrect according to Sforzando.

To make it load one must change:
`#define $KeyCrash2     57 // Crash Cymbal 2 (Bow)`
to
`#define $KeyCrash2 57 // Crash Cymbal 2 (Bow)`

It seems to not like multiple spaces after define (and this one only, most curiously).
After this change, both regions will be on the key 57.

**Comment by paulfd** [comment]
From these files

[GSCW-DrumKit-1.zip](https://github.com/sfztools/sfizz/files/4623912/GSCW-DrumKit-1.zip)

@redtide gave them to me.

The spaces I have to admit I am not sure, I may have seen this somewhere else though... The book says nothing. And it does make sense to strip the whitespace no?

**Comment by jpcima** [comment]
ARIA does not left-trim after `#define`, more in #225

**Comment by paulfd** [comment]
Ok, I think we can be pragmatic and factual. The book does very little to specify the behavior of defines, and ARIA clearly is the target against which most library are built today so for this type of things I think we go their way.

When everything is wrapped up we should consider documenting the behavior on sfzformat to help people building libraries be mindful of this and not attempt to be too crazy with this facility.

**Comment by jpcima** [comment]
Closing, and I will redo this better in new PRs.

**Pull request closed without merging**
