### PR TITLE
Don't require an explicit hikey/key=-1 to trigger on CC

### LINKED ISSUE #239: Trigger on CC incorrect
The following example will trigger on CC in ARIA.
It does not on sfizz, unless `key=-1` is written explicitly.
Surely it's another case of ARIA where `-1` and `<not set>` have identical semantic.

```
<region>
sample=*sine
start_locc16=100
start_hicc16=127
```

### PR DESCRIPTION
**Pull request by paulfd**
Closes #239

### CODE REVIEW

**Comment by jpcima** [comment]
so `lokey` is not concerned by -1 values?

**Comment by paulfd** [comment]
Well, in the PLJ page they said only key and hikey. Apparently it did not catch on 🙂

**Review by jpcima — APPROVED** [review]

**Comment by paulfd** [comment]
Updated so that you may actually trigger on both CC and key, matching Sforzando's behavior. @jpcima if you're still OK I'll merge it now.

**Comment by jpcima** [comment]
Sure yes, it makes sense, please do.

**Pull request merged**
