### PR TITLE
Shared FilePool

### PR DESCRIPTION
**Pull request by KKQ-KKQ**
In iOS/iPadOS, an AU plugin's process is shared.
In order to reduce its memory, I made this changes.

It's Ok if this PR is not approved.

### CODE REVIEW

**Comment by paulfd** [comment]
Thanks, this is a longstanding request! I'll need some time to review it though, global structures can be a bit tricky in this context.

**Comment by KKQ-KKQ** [comment]
As errors occur, I temporally close this PR.

**Comment by redtide** [comment]
you can use draft PRs in GitHub if needed, it's not a problem if there are failures with CI anyway.

**Comment by paulfd** [comment]
Yeah you can keep using this PR to test if needed, no worries.

**Pull request closed without merging**
