### PR TITLE
CI: added build timeout

### PR DESCRIPTION
**Pull request by redtide**
@KKQ-KKQ

### CODE REVIEW

**Comment by KKQ-KKQ** [comment]
Thanks you. but I don't know whether it's correct or not. Where can we check the actual timeout?

I thought abseil had issues but the tests succeeded.
I was wrong....

**Comment by redtide** [comment]
> Where can we check the actual timeout?

Doing some average of previous build timings I guess, but this can be something we can manage later, hope these ones are good enough for now.

>I thought abseil had issues but the tests succeeded.
I was wrong....

No worries, this can happen again in other contexts so it's good to have anyway.
I wait a bit for Paul before merging, have you found some way meanwhile to get it build with new Abseil?

**Comment by KKQ-KKQ** [comment]
With the following script on my mac, some tests fail on Abseil 20240116.rc1.
The tests don't fail on Abseil 20230125.3.
```
#!/bin/bash
BT=RelWithDebInfo
cmake -B build -S . -D SFIZZ_ASAN=ON -D CMAKE_BUILD_TYPE=${BT} -D SIZZ_SHARED=ON -D SFIZZ_TESTS=ON  &&\
cmake --build build --parallel 4 --target sfizz_tests --config ${BT} &&\
ctest --output-on-failure --stop-on-failure --test-dir build --build-config ${BT}
```

**Comment by redtide** [comment]
Oh, I didn't know we used release candidate versions other than LTS, so at this point maybe it worth to try the current 20240116.0 of 2 weeks ago maybe?

**Comment by KKQ-KKQ** [comment]
Issue #1240
20240116.0 also fails.
20230802.1 works.
20230802.rc2 also works.

**Pull request merged**
