### PR TITLE
Reorganize VST SDK as submodules

### PR DESCRIPTION
**Pull request by jpcima**
No patch for the moment, just a try

### CODE REVIEW

**Comment by jpcima** [comment]
Since it works, what do you think to merge it now?
This should allow to make the OBS builds of VST plugins.

**Comment by paulfd** [comment]
Sure. Do you want to proceed with the patching in the build stage ?

**Comment by paulfd** [comment]
If you're confident you can merge it directly no problem 😄

**Comment by jpcima** [comment]
I will fork vstgui later. For now I posted them an issue report with links to info and patch.
I don't expect a quick answer (or even maybe an answer), we'll see.

First I will update OBS builds to produce the VST plugin.

**Pull request merged**
