### PR TITLE
Add the sfz flattener in-tree

### PR DESCRIPTION
**Pull request by paulfd**
Previous version (with the old parser) at https://github.com/sfztools/sfz-flat.

### CODE REVIEW

**Comment by jpcima** [comment]
May this program be a duplicate of devtools/Preprocessor, or it does something else ?

**Comment by paulfd** [comment]
It is a bit of a duplicate, except for the option to flatten the file. I forgot about these devtools...

**Comment by jpcima** [comment]
If this offers better functionality, it's fine to replace the existing with this, and rename if desired.

**Comment by paulfd** [comment]
The functionality is mostly the same and this one has the option to add defines so it's nice. No worries.

**Pull request closed without merging**
