### PR TITLE
Add support for opcodes lotimer/hitimer

### PR DESCRIPTION
**Pull request by essej**
While not widely supported or well documented, is very useful especially when triggering a note with on_locc/on_hicc to prevent a bunch of retriggers.

The region will trigger as long as the elapsed time from the note-on of the most recently triggered region in the current polyphony group is between lotimer and hitimer amount of seconds. lotimer default 0, hitimer default is max_float.

Example use: to preventing a region from retriggering too quickly, set lotimer=0.1

### CODE REVIEW

**Comment by paulfd** [comment]
Thanks for the MR! Same as the other, I'd like to add a some form of testing for this, do you have the typical use case that triggered you to make this change?

**Comment by essej** [comment]
Sure, as mentioned in the comment above, my motivating use case was a way to rate-limit triggers from a region set up to be triggered via CC events using on_locc/on_hicc . For example:
```ini
<region>
group=1
on_locc4=0 on_hicc4=0
lotimer=0.1
sample=hihatFoot_OH_MP_1.wav
```

Which is an example where you could have a pedal which is setup in an expression input that sends CC values, to trigger when the value hits 0, but to not trigger again until after 0.1 seconds elapses, and effectively debounces the input which may jitter around zero.

I saw this unimplemented opcode in the spec, which did exactly what I wanted, assuming I decoded the meaning correctly, since it appears to be unimplemented by most other SFZ engines.

I haven't looked into how the tests are setup, should I perhaps add something in RegionTriggersT.cpp to test this opcode, or in some other place?

**Comment by paulfd** [comment]
The implem looks great. I'll add some parsing and messaging tests, and for this one we can test triggering too.

**Comment by paulfd** [comment]
I added the tests, tell me if everything looks reasonable!

**Pull request merged**
