### PR TITLE
Update the VST plugin

### PR DESCRIPTION
**Pull request by jpcima**
- add tuning
- add tuning UI
- add value labels
- restore file paths on UI reopened
- update the state format

### CODE REVIEW

**Comment by paulfd** [comment]
I rebased and changed the number of voices. I gave it a push in Reaper and it seems to work nicely! Let CI run and we can merge it from my side :slightly_smiling_face:

**Review by paulfd — APPROVED** [review]

**Comment by jpcima** [comment]
You're right on this, it needs to edit `SfizzVstState.h` and change 256 to 64.

**Comment by paulfd** [comment]
I did it wrong in (https://github.com/sfztools/sfizz/pull/282/commits/80d4eaf9c7de9278b65bdd1753ad6a17274c1c76)?

**Comment by paulfd** [comment]
I have to admit I'm relying alot on you for the VST internals :D

**Comment by jpcima** [comment]
It looks fine; I hadn't noticed about this one.
I read that LV2 has the lower bound to 8, do you want to make it the same here ?

**Pull request merged**
