### PR TITLE
Prepping small things for the release

### PR DESCRIPTION
**Pull request by paulfd**
I changed the author name, and added version tags for docstrings.

### CODE REVIEW

**Review by redtide — APPROVED** [review]

**Comment by redtide** [comment]
Changes are OK to me, wondering maybe "SFZTools Team" as name (more explicit)?

**Comment by jpcima** [comment]
also bump `LV2PLUGIN_VERSION_MICRO` in LV2Config

**Comment by paulfd** [comment]
micro or minor? We've added parameters this turn.

**Comment by jpcima** [comment]
actually it's minor not micro

>The minor version MUST be incremented when backwards (but not forwards) compatible additions are made, for example the addition of a port to a plugin.

**Pull request merged**
