### PR TITLE
SIMD-accelerated string resonator

### PR DESCRIPTION
**Pull request by jpcima**
This is an update of the strings resonator with SSE and AVX acceleration.
It's CPU-dispatched at runtime. I added an external library to detect CPU features, so a lot of file additions come from there.

4 strings are going to be synthesized at a time with SSE, and 8 with AVX.

It was necessary to make some CMake changes to permit applying specific compile flags to SIMD sources.
Also `Buffer` was edited to allow 32-byte alignment, which is AVX's register size.

There is a defect at the moment; some times AVX crashes and some times not.
Probably there's an alignment defect somewhere, which I don't have identified for the moment.
I tagged `alignas` on the 2 classes where it seemed appropriate, it didn't help.

### CODE REVIEW

**Comment by jpcima** [comment]
A backtrace of this problem
```
==238827== 
==238827== Process terminating with default action of signal 11 (SIGSEGV): dumping core
==238827==  General Protection Fault
==238827==    at 0x112930: sfz::fx::ResonantStringAVX::ResonantStringAVX() (src/sfizz/effects/impl/ResonantStringAVX.h:36)
==238827==    by 0x111D49: sfz::fx::ResonantArrayAVX::setup(float, unsigned int, float const*, float const*, float const*, float const*) (src/sfizz/effects/impl/ResonantArrayAVX.cpp:33)
==238827==    by 0x10C251: AddArray_StringResonator_AVX_Benchmark::BenchmarkCase(benchmark::State&) (benchmarks/BM_stringResonator.cpp:89)
==238827==    by 0x10C965: benchmark::Fixture::Run(benchmark::State&) (benchmark.h:1063)
==238827==    by 0x48D0A57: benchmark::internal::BenchmarkInstance::Run(unsigned long, int, benchmark::internal::ThreadTimer*, benchmark::internal::ThreadManager*) const (in /usr/lib/libbenchmark.so.0.0.0)
==238827==    by 0x48BD268: ??? (in /usr/lib/libbenchmark.so.0.0.0)
==238827==    by 0x48BDB2D: benchmark::internal::RunBenchmark(benchmark::internal::BenchmarkInstance const&, std::vector<benchmark::BenchmarkReporter::Run, std::allocator<benchmark::BenchmarkReporter::Run> >*) (in /usr/lib/libbenchmark.so.0.0.0)
==238827==    by 0x48D5ACB: benchmark::RunSpecifiedBenchmarks(benchmark::BenchmarkReporter*, benchmark::BenchmarkReporter*) (in /usr/lib/libbenchmark.so.0.0.0)
==238827==    by 0x10C5A9: main (benchmarks/BM_stringResonator.cpp:103)
==238827== 
```

**Comment by jpcima** [comment]
In aborts on new[], while creating the array of `ResonantStringAVX`.
The class `ResonantStringAVX` contains instance variables of type `__m256`.

The `__m256` are {}-initializer.

I guess it's this initialization that writes non-aligned addresses, because the `ResonantStringAVX` pointer was not aligned to 32-byte.

**Comment by jpcima** [comment]
The alignment problem was resolved with help of the `Buffer` class.
See below for benchmark results. (the benchmark range is the number of strings)

```
020-04-02 15:42:34
Running ./build/benchmarks/bm_stringResonator
Run on (8 X 3600 MHz CPU s)
CPU Caches:
  L1 Data 32K (x4)
  L1 Instruction 64K (x4)
  L2 Unified 512K (x4)
  L3 Unified 4096K (x1)
Load Average: 3.18, 2.24, 1.33
***WARNING*** CPU scaling is enabled, the benchmark real time measurements may be noisy and will incur extra overhead.
------------------------------------------------------------------------------
Benchmark                                    Time             CPU   Iterations
------------------------------------------------------------------------------
AddArray/StringResonator_Scalar/1       259242 ns       258281 ns         2696
AddArray/StringResonator_Scalar/4      1026544 ns      1023187 ns          676
AddArray/StringResonator_Scalar/16     4205782 ns      4051976 ns          167
AddArray/StringResonator_Scalar/64    16771449 ns     16166598 ns           43
AddArray/StringResonator_Scalar/128   33589054 ns     32384596 ns           21
AddArray/StringResonator_SSE/1          326359 ns       314222 ns         2308
AddArray/StringResonator_SSE/4          319646 ns       307925 ns         2236
AddArray/StringResonator_SSE/16        1120470 ns      1079579 ns          653
AddArray/StringResonator_SSE/64        4447906 ns      4283852 ns          163
AddArray/StringResonator_SSE/128       8689821 ns      8371019 ns           82
AddArray/StringResonator_AVX/1          421517 ns       418330 ns         1655
AddArray/StringResonator_AVX/4          426996 ns       424557 ns         1678
AddArray/StringResonator_AVX/16         796011 ns       765944 ns          817
AddArray/StringResonator_AVX/64        3150497 ns      3026680 ns          246
AddArray/StringResonator_AVX/128       5987364 ns      5765760 ns          113
```

**Comment by paulfd** [comment]
Wow this parallelize nicely. Well done!

**Comment by jpcima** [comment]
It's good to merge as I'm concerned.

The only problem, which has been worked around partially, it's that that cmake in MOD devices does not set `CMAKE_SYSTEM_PROCESSOR` correctly, and ended up passing the flag `-mavx`.

The problem is not new, but it got annoying with new SIMD needs.

The adequate way is to write a cmake toolchain file for MOD, which I prefer not do in the scope of this PR.

**Pull request merged**
