### PR TITLE
Travis build with MinGW (better)

### PR DESCRIPTION
**Pull request by jpcima**
- added environment.sh, a global script for such things as `PATH` across scripts
- cross compiler and libs in docker container
- added a helper to run commands under container, or machine, depending on build type

### CODE REVIEW

**Comment by paulfd** [comment]
For me it looks OK but I'm not really that much of a Travis expert ! Side note though: can we use a similar idea to build the statically linked versions for Linux using docker?

**Comment by redtide** [comment]
It looks OK to me, I was not sure about one fail to find a file but it seems an authorization issue because the fork, so I think we can merge.
@paulfd yes, sure.

**Review by redtide — APPROVED** [review]
OK for me.

**Comment by paulfd** [comment]
For the change in ghc, is the warning bad? I'd rather either push this upstream or just ignore the warning "manually", it may cause problems for when we update the header from upstream.

**Comment by jpcima** [comment]
I took this liberty because:
- it doesn't affect the build result; updating would just make the warning come back
- it's a warning from a header, so it propagates its occurrence into many compile units
- we can submit this to upstream as PR, in the meantime
- it's a result of -Wextra, as result of a warning which Windows dynamic loading forces on us and we don't really have any way to work around.

There is some information about this particular warning:
https://debarshiray.wordpress.com/2019/04/01/about-wextra-and-wcast-function-type/

**Comment by paulfd** [comment]
Okay let's propose this upstream and merge meanwhile then! Thanks!

**Pull request merged**
