### PR TITLE
fix tuning root

### LINKED ISSUE #1199: Tuning root key is ignored.
Tuning root key is ignored.

I try loading Scala file and changing the root key but the key seems to be ignored.

### PR DESCRIPTION
**Pull request by KKQ-KKQ**
fix #1199

### CODE REVIEW

**Comment by paulfd** [comment]
Hi, thanks for the MR! Just FYI I'm not really an expert in this part of the code and I don't have alot of experience with tuning variations besides setting temperaments on an electric organ.

 Before the change, the code was equivalent to `Tunings::startScaleOnAndTuneNoteTo(60, rootKey, rootFrequency);` with `rootFrequency` a corrected one from the parameter. Now you changed it to `Tunings::startScaleOnAndTuneNoteTo(60, rootKey, tuningFrequency);` and the given `tuningFrequency` always applies to midi note 69, so A4. I'm guessing it boils down to a naming convention of what's the "root key": is it the "scale start" or the "tuning reference"? Can you give me some context about all this?

**Comment by KKQ-KKQ** [comment]
`Tunings::startScaleOnAndTuneNoteTo(60, rootKey, rootFrequency)` and `Tunings::startScaleOnAndTuneNoteTo(rootKey, 69, tuningFrequency)` are completely different.
The first one sets the start of the scale to 60 (C4).
The latter sets the start of the scale to rootKey.

**Comment by KKQ-KKQ** [comment]
"Root key" is the "scale start".
In order to shift the scale tuning, it is.

**Comment by paulfd** [comment]
I guess my question is: when using scala, the root key is usually the start of the scale rather than the reference note for the tuning frequency?

**Comment by paulfd** [comment]
Thanks for the answer. 

Just FYI, should is a pretty strong word.

**Comment by KKQ-KKQ** [comment]
I'm sorry. I am not good at English language.

**Comment by paulfd** [comment]
No worries :)

**Pull request merged**
