### PR TITLE
Ring modulation

### PR DESCRIPTION
**Pull request by jpcima**
Implements ring modulation, as described in the cakewalk book

### CODE REVIEW

**Comment by jpcima** [comment]
Ring modulation example
```
<control>
set_hdcc21=0.5

<region>
sample=*saw
oscillator=on
oscillator_mode=0
oscillator_multi=2
oscillator_detune=25
oscillator_mod_depth=100
oscillator_mod_depth_oncc21=100
```

**Comment by paulfd** [comment]
Does the book specify if we can have different waveforms for the multiple oscillators?

**Comment by jpcima** [comment]
There is no indication about this whatsoever, although this is indeed important to modulation synthesis.
Under rapture, you can process RM, but only by user interface, not via SFZ oscillator opcodes; modulator and carrier can select different waves.
I make this choice by naively following what unison did; assign identical waves to all the oscillators.
For distinct waves, it will require a SFZ extension.

**Comment by jpcima** [comment]
superseded by #436 (which includes a fix for unison)

**Pull request closed without merging**
