### PR TITLE
Corrected #63

### PR DESCRIPTION
**Pull request by paulfd**
- The envelope does not sustain if the region has `trigger=release`
- Change the envelope setup to pass the region rather than
individual envelope parameters

### CODE REVIEW

**Comment by jpcima** [comment]
This makes sense to me.

What about more aggressive voice stealing, would it be good to do something about it?
(eg. one note arrives as polyphony is full, kill oldest voice and replace it)

**Review by jpcima — APPROVED** [review]

**Comment by paulfd** [comment]
I have a mechanism now in place. The idea is to take all voices that are in release state and take the voice with the lowest score -- and still below a threshold.
Reading it I realize I'm sorting the wrong array, and that there's a sort of mixup of logic there so I'll fix it :P

This mechanism was never active because the voice was never in a release state. Saying this I also realize that the above fix will still not put the voice in release state, so I'll hold off merging for now.

**Comment by paulfd** [comment]
Ah no I'm sorting by the longest running voice that can be stolen and then finding one that has power below a threshold. See [here](https://github.com/sfztools/sfizz/blob/8941f0a8004d2af54966a245e7ad13a84ed87097/src/sfizz/Synth.cpp#L340).

Maybe just taking the one with the lowest power would be simpler actually. Even if it ran for a shorter time, we don't really care.

**Comment by jpcima** [comment]
I would say to elect the voice which has the greatest age, first among the releasing ones, and second among the others.

**Comment by paulfd** [comment]
Ok now both the voice and the envelope should be in release state together.

**Comment by paulfd** [comment]
Benchmarks updated now, so I'll merge this as soon as the CI ends.

**Pull request merged**
