### PR TITLE
Add a build helper for DPF

### PR DESCRIPTION
**Pull request by jpcima**
This adds a build helper for DPF plugins with sfizz.
There is an explanation how to use it at the top of the file.

@rghvdberg

### CODE REVIEW

**Comment by jpcima** [comment]
Abseil seems to pull more deps under `DEBUG=true`, hence I updated to take it in consideration.

@pdesaulniers hi, possibly it interests you to check this work as well.

**Review by paulfd — APPROVED** [review]

**Comment by paulfd** [comment]
Btw, how come we pull in so many unrelated things from abseils? Like the time zone and synchronization primitives. I think we mostly use optional, span, the atoi-type helpers and a couple string functions here and there no? And the string_views..

**Comment by jpcima** [comment]
I've included there the strict necessary set of libraries which is needed to please the linker, not one more.
Their respective source listings are from abseil's subdirectory CMakeLists, listed under `SRCS`.

**Comment by paulfd** [comment]
The question was more aimed at absl than your script :slightly_smiling_face:

**Pull request merged**
