### PR TITLE
Multiple outputs

### LINKED ISSUE #9: [FR] Add support for multiple (stereo) output channels
Relevant opcode:

* https://sfzformat.com/opcodes/output

The main use case is SFZ files for drum sets, where one would want to route different drum sounds to different output channels, so they can be routed to different track in the DAW, e.g. for treating them with different effects or do custom panning.

### PR DESCRIPTION
**Pull request by paulfd**
Closes: #9 

As a first step, this creates identical copies of the effect buses described in the SFZ file on each output. The effect buses also then provide the temporary buffers that are mixed onto the actual output. The render methods have been updated to actually handle more than 1 stereo channel as an output. If there are more outputs in the SFZ file than in the buffer-to-render, SFZ outputs are "wrapped" onto the available rendering output.

### CODE REVIEW

**Comment by jpcima** [comment]
What do you think of the idea from #207 ?
The duplicated multi-out vs the bus output seem conflicting approaches.

**Comment by paulfd** [comment]
Actually I was thinking that the `auxN` buses could use the idea from #207, and the `main` and `fxN` buses would be duplicated.

The main advantage I see with this solution is that it's pretty transparent for users: you put an effect and it appears on all outputs by default, so it kind of does what you'd expect regardless if you have one or more outputs. If you need finer grained effect then you could use aux buses, to be implemented of course.

One alternative would be to specify the output each effect applies to, in which case it's a bit more involved and verbose.

**Comment by jpcima** [comment]
Sure, but on the other hand, it creates difficulty with some future perspectives.
In particular, if one wants to give introspection and edition abilities into a graph-like processor.
I'm thinking of script API in particular.

**Comment by paulfd** [comment]
So you'd rather that we have the `output` opcode on the effects, so that all effects are on the output 0 buses by default but you could put it on another one?

Either way you can introspect 😄

**Pull request merged**
