### PR TITLE
Detect SIMD availability from compiler

### PR DESCRIPTION
**Pull request by jpcima**
#50

Remove configure-time checks for SIMD features, and replace with compile-time ones.

Add SIMDConfig.h where detection magic happens.

Add all 3 source files to all builds inconditionnally, skip the parts not needed with use of preprocessor conditionals.
`    sfizz/SIMDSSE.cpp    sfizz/SIMDNEON.cpp    sfizz/SIMDDummy.cpp`

### CODE REVIEW

**Comment by paulfd** [comment]
Actually all the stuff from https://github.com/sfztools/sfizz/blob/efccb7ae446145376a59016781ece093aebb2a47/src/sfizz/Config.h#L56 could go into `SIMDConfig.h` and be per architecture. That was kinda the goal at first.

**Comment by paulfd** [comment]
BTW remove the ARM compiler flags too, I copied them from a raspberry forum but they brought me only pain and sadness...

**Comment by jpcima** [comment]
At this point, it is nearly the file `SfizzSIMDSourceFilesCheck.cmake` which can go altogether.

**Comment by paulfd** [comment]
Indeed it's not very useful anymore !

**Review by paulfd — APPROVED** [review]

**Pull request merged**
