### PR TITLE
Correct a bug with dynamic updates on offed EGs

### LINKED ISSUE #2: Missing notes
Not sure if it happens in the JACK client or the SFZ engine, but compared to other sfz players I notice a definitive lack of notes played when using a few SFZs I have around.

This is one such case https://musical-artifacts.com/artifacts/460

Is there a polyphony limit? If so, it seems very low.

### PR DESCRIPTION
**Pull request by paulfd**
Closes: #2 

@falkTX if you want to check that this indeed solves your problem.

### CODE REVIEW

**Comment by falkTX** [comment]
@paulfd note stealing is much improved now, quickly using notes in succession triggers things properly, this is great to see thanks!

**Comment by falkTX** [comment]
black midi still makes sfizz go bad, but that might be asking too much haha :sweat_smile: 
can recommend trying that out, https://github.com/x42/midigen.lv2 is a quick way to test that with its included tetris black midi song

**Comment by paulfd** [comment]
I've received the Dwarf, and indeed performance is not amazing 😓 I'll try to improve it when I find the time (and unpile everything else)

**Comment by falkTX** [comment]
Note that on dwarf there is an issue where RT operation stop while allocating memory on unrelated processes.
I was unable to find the reason why, but it is very easy to trigger by running a memory testing tool while dwarf is doing its business. Memory allocations can induce xruns.
This does not happen on duo or duox...

So the performance issues might be related, due to sfizz reallocating things on its background thread.
One possible thing to try is a fixed pool of memory. It will trigger xruns when plugin is first loaded, but then should be stable.

And yeah, I tried many things for priorities and cpu scheduling stuff. My current theory is on memory not being setup in the best way by the bootloader.

**Pull request merged**
