### PR TITLE
Add VST info panel

### PR DESCRIPTION
**Pull request by jpcima**
Adds an info panel which displays VST active polyphony and other things. @kinwie

Capture du 2020-08-12 19-24-24

### CODE REVIEW

**Comment by kinwie** [comment]
This is great!
I just think better to have Globals than Curves though

**Comment by paulfd** [comment]
Well since I thought that there was only 1 global per file, there are no counters in sfizz for the number of globals :P

**Review by paulfd — APPROVED** [review]

**Comment by kinwie** [comment]
Ohh okay, so we are on the way to having more headers then :))

**Comment by jpcima** [comment]
`<global>` and `<control>` are missing.
It would be simply the number of appearances of these headers.
Also missing is the name of the last sample which has been triggered.

**Pull request merged**
