### PR TITLE
Make the opposing curves equal at MIDI value 64

### PR DESCRIPTION
**Pull request by jpcima**
Make the opposing curves equal at MIDI value 64, defined as center by MIDI specs.
- [0,1] should have center at 0.5
- [-1,1] should have center at 0
- Xfades should have center at 1/√2

TODO: the tests

### CODE REVIEW

**Review by paulfd — APPROVED** [review]

**Comment by paulfd** [comment]
I added/updated the tests to match the behavior, and I also changed the `normalizeXXX` functions so that midi 64 is 0.5f (which in return already corrects many tests :slightly_smiling_face:).

I'm ok for the merge!

**Review by paulfd — APPROVED** [review]

**Comment by jpcima** [comment]
Nice thanks for updating this. I'll add just a few observations.

- there was a claim on the main channel that ARIA does not center at 64. This is based on Cakewalk.
- also the hdcc thing came later based on some sample set needs, and this raises a new problem: the hdcc 0.5 is supposed to be center, but this becomes a mismatch to cc7bit when (de)normalizing from one to another.

**Comment by paulfd** [comment]
Well I think this would be better practice to center at 64 anyway... for the (de)normalization, I updated the normalizing, you'd want to adapt the denormalizing too? Not super pretty but

```cpp
template<class T, absl::enable_if_t<std::is_integral<T>::value, int> = 0>
inline CXX14_CONSTEXPR constexpr T denormalize7Bits(float value)
{
    if (value < 0.0f)
        return T { 0 };

    if (value > 1.0f)
        return T{ 127 };

    if (value <= 0.5f)
        return static_cast<T>(value * 128.0f);

    return T{ 64 } + static_cast<T>((value - 0.5f) * 126.0f);
}
```
would work I guess?

**Comment by paulfd** [comment]
I added the previous function and simple tests.

**Comment by paulfd** [comment]
This one looks OK to me now, if you want to undraft and merge it

**Comment by jpcima** [comment]
This one, I've come to wonder if really it's a good idea, after dealing with ARIA hdcc.

ARIA has used its own extensions to deal with this problem: hdcc and icurvecc.
This is going to modify this behavior in possibly undesired ways.

This commit permits conforming to some Cakewalk behavior, but then it disturbs normal behavior of these ARIA extensions, it's the problem. (also possibly things as on_lohdcc)
It sits in the middle of both ARIA and CW but in a not very satisfying way.

**Comment by paulfd** [comment]
You mean that since ARIA does not care to center at 64 we maybe should just use the extensions for "precise" centering?

**Comment by kinwie** [comment]
If this is not finalized yet, I suggest to do ARIA, hdcc=0.5. I'm guessing, centering Midi value 64 might disturb the curve?

**Pull request closed without merging**
